# Generated by Django 4.2.10 on 2024-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memo',
            new_name='content',
        ),
    ]
